---
- name: Restart servers serially
  hosts: all
  serial: 1
  become: yes
  tasks:
    - name: Restart server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      register: reboot_result

    - name: Log reboot status
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} rebooted: {{ reboot_result.rebooted }}"
